// policy_macros.do
// -----------------------------------------------------------------
// Runs two toy policy counterfactuals and writes the results out as
// LaTeX \newcommand macros.
//
// Part 1 is (lightly adapted) from Florian Oswald (2026),
//   "Are Your in-text Numbers Correct? Do They Match Your Table?"
//   JPE Data Editor Blog,
//   https://jpedataeditor.github.io/posts/20260910-latex-macros/
// Part 2 (numbers from a real regression) was added for this tutorial.
// -----------------------------------------------------------------

clear all                              // start from a clean Stata session
set more off                           // don't pause output with --more--

// =================================================================
// Part 1: two toy policies
// =================================================================

// ---- Policy A: a toy "run" of counterfactual A ----
scalar baseline_welfare = 100          // welfare level under the status quo
scalar new_welfare_A    = 102.3        // welfare level after applying policy A
scalar pct_change_A     = (new_welfare_A / baseline_welfare - 1) * 100
scalar n_reass_A        = 64           // a second, unrelated output: a count

// ---- Policy B: a second, independent counterfactual ----
scalar new_welfare_B    = 101.1        // welfare level after applying policy B
scalar pct_change_B     = (new_welfare_B / baseline_welfare - 1) * 100
scalar n_reass_B        = 12

// ---- decide the "winner" -- a STRING output, not a number at all ----
local winner "B"                       // default guess
if pct_change_A > pct_change_B local winner "A"   // overwrite if A wins

// ---- format every number to a plain string BEFORE writing it ----
// string(x, "%4.1f") pads to a field width of 4, so strtrim() removes the
// resulting leading space.
local welfareA = strtrim(string(pct_change_A, "%4.1f"))
local welfareB = strtrim(string(pct_change_B, "%4.1f"))
local nreassA  = strtrim(string(n_reass_A,    "%2.0f"))
local nreassB  = strtrim(string(n_reass_B,    "%2.0f"))

// ---- open the macro file for writing (overwrites any existing file) ----
tempname fh                            // a name for the open file
file open `fh' using "results_macros.tex", write replace text

// header comment: tells your coauthors not to edit this file by hand
file write `fh' "% Auto-generated by policy_macros.do -- do not edit by hand." _n
file write `fh' "% Generated: `c(current_date)' `c(current_time)'" _n _n

// percentages: "\%" is the literal, escaped LaTeX percent sign
file write `fh' "\newcommand{\WelfareA}{`welfareA'\%}" _n
file write `fh' "\newcommand{\WelfareB}{`welfareB'\%}" _n _n

// integer counts: no decimals, no percent sign
file write `fh' "\newcommand{\NReassA}{`nreassA'}" _n
file write `fh' "\newcommand{\NReassB}{`nreassB'}" _n _n

// a text label -- Stata locals interpolate directly into the string
file write `fh' "\newcommand{\PreferredPolicy}{`winner'}" _n

// =================================================================
// Part 2: numbers from a real regression
// =================================================================

sysuse auto, clear                     // 1978 automobile data, ships with Stata
regress price mpg weight

local coefmpg = strtrim(string(_b[mpg],  "%9.1f"))   // coefficient on mpg
local sempg   = strtrim(string(_se[mpg], "%9.1f"))   // its standard error
local nobs    = strtrim(string(e(N),     "%9.0f"))   // number of observations

file write `fh' _n "% ---- regress price mpg weight ----" _n
file write `fh' "\newcommand{\CoefMpg}{`coefmpg'}" _n
file write `fh' "\newcommand{\SeMpg}{`sempg'}" _n
file write `fh' "\newcommand{\NObs}{`nobs'}" _n

file close `fh'                        // flush the buffer and close the file

// echo the file back into the log, so the log itself documents what was written
type "results_macros.tex"
