# Helpers for the slides.
#
# The slides never contain copies of the example code: they read it from the
# files in examples/, so that what participants see on the slide is exactly
# what is in the repository. Use in a chunk with results='asis', echo=FALSE.

# Show (part of) a file as a code block.
#   from, to: line numbers, or a piece of text that identifies the line
#             (the first line containing it; 'to' is searched in the lines
#             after 'from')
#   fence:    use "````" when the file itself contains ``` fences
show_file <- function(path, from = 1, to = NULL, lang = "", fence = "```") {
  lines <- readLines(here::here(path), warn = FALSE)
  locate <- function(x, after = 1) {
    if (is.numeric(x)) return(x)
    i <- grep(x, lines, fixed = TRUE)
    i <- i[i >= after][1]
    if (is.na(i)) stop("Text not found in ", path, ": ", x)
    i
  }
  start <- locate(from)
  end   <- if (is.null(to)) length(lines) else locate(to, after = start + 1)
  cat("\n", fence, lang, "\n",
      paste(lines[start:end], collapse = "\n"),
      "\n", fence, "\n\n", sep = "")
}

# Show a file if it exists (e.g., output generated by tests/test-stata.sh),
# otherwise show the fallback text.
show_file_or <- function(path, fallback, ...) {
  if (file.exists(here::here(path))) {
    show_file(path, ...)
  } else {
    cat("\n", fallback, "\n\n", sep = "")
  }
}

# Show R inline code on a slide without knitr running it:
#   `r inline_r("nrow(auto)")`  displays  `r nrow(auto)`
inline_r <- function(code) {
  paste0("`` `r ", code, "` ``")
}

# Include an image if it exists, otherwise show the fallback text.
image_or <- function(path, fallback, attrs = "") {
  # path is relative to presentation/, like all image paths in the slides
  if (file.exists(here::here("presentation", path))) {
    cat("\n![](", path, ")", attrs, "\n\n", sep = "")
  } else {
    cat("\n", fallback, "\n\n", sep = "")
  }
}
